config/routes.rb
Enterprise::Application.routes.draw do
  resources :profiles

  get "orderitems/index"

  get "orderitems/show"

  get "orderitems/new"

  get "orderitems/edit"

  

devise_for :users do
resources :orders
end
resources :orders do
resources :orderitems
end

  get "cart/index"

  get "site/about"

  get "site/contact"

  get "site/home"
  
  get "items/category"

  resources :items

match '/about' => 'site#about'
match '/contact' => 'site#contact'
match '/home' => 'site#home'
match '/cart' => 'cart#index'
match '/cart/:id' => 'cart#add'
match '/cart/remove/:id' => 'cart#remove'
match '/clearCart' => 'cart#clearCart'
match '/checkout' => 'cart#createOrder'

match '/Admin' => 'user#admin_login'
match '/logout' => 'user#logout'

match '/myprofile' => 'profiles#myprofile'

match '/category/:id' => 'items#category'

match '/search' => 'items#search'

root :to => 'site#home'

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_filter :authenticate_user!

def add
  id = params[:id]
    cart = session[:cart] ||= {}
      cart[id] = (cart[id] || 0) + 1
        redirect_to :action => :index
end

def index
  @cart = session[:cart] || {}
end

def change
  cart = session[:cart]
    id = params[:id];
      quantity = params[:quantity].to_i
        if cart and cart[id]
          unless quantity <= 0
            cart[id] = quantity
      else
        cart.delete id
end
end


redirect_to :action => :index
end

def checkout
  flash[:notice] = "CHECKOUT IS NOT IMPLEMENTED YET!!!"
    redirect_to :action => :index
end

def remove
  id = params[:id]
    cart = session[:cart] 
      cart.delete id
        redirect_to :action => :index
end

def clearCart
  session[:cart] = nil
    redirect_to :action => :index
end


def createOrder
# Step 1: Get the current user
  @user = current_user
# Step 2: Create a new order and associate it with the current user
    @order = @user.orders.build(:order_date => DateTime.now)
    @order.save
# Step 3: For each item in the cart, create a new item on the order!!
      @cart = session[:cart] || {} # Get the content of the Cart
      @cart.each do | id, quantity |
      item = Item.find_by_id(id)
      @orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price => item.price)
      @orderitem.save
	#redirect_to :action => :checkout_message
    end
 end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<h1>Cart</h1>

<% if @cart.empty? %>
	<p>There is nothing in your shopping Cart</p>
<% end %>

<% total = 0 %>


<table>
	<tr>
		<td class="legend"></td>
		<td class="legend">Item</td>
		<td class="legend">Price</td>
		<td class="legend">Qty</td>
		<td class="legend">Total</td>
	</tr>

<% @cart.each do | id, quantity | %>
	<% item = Item.find_by_id(id) %>
	<tr>
		<td>
			<div id="image">
				<%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
			</div>
		</td>
		<td class="title"><%= link_to item.title, item %></td>
		<td class="price"><%= number_to_currency(item.price, :unit => "€") %></td>
		<td class="quantity"><%= quantity %><br /></td>
		<td class="price">
		<%= number_to_currency(quantity * item.price, :unit => "€") %>
		</td>
		<td><a href="/cart/remove/<%=item.id%>"></a></td>
	</tr>
	<% total += quantity * item.price %>
<% end %>
	
	<tr>
		<td colspan="4">
			<div class="total">Total:</div>
		</td>
		<td>
			<div class="price"><%= number_to_currency(total, :unit => "€") %></div>
		</td>
	</tr>
</table>

<p>
	<%= link_to 'Keep Shopping', items_path %>
	<%= link_to 'Empty Cart', clearCart_path %>
	<%= link_to 'Proceed to Check Out', checkout_path %>
	
</p>

app/views/cart/index.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
<p>Your Cart is empty.</p>
<% end %>
<% total = 0 %>
<table class="cart">
<tr>
<td class="legend"></td>
<td class="legend">Item</td>
<td class="legend">Price</td>
<td class="legend">Qty</td>
<td class="legend">Total</td>
</tr>
<% @cart.each do | id, quantity | %>
<% item = Item.find_by_id(id) %>
<tr>
	
<td>
<div class="image">
<%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
</div>
</td>

<td class="title"><%= link_to item.title, item %></td>
<td class="price"><%= number_to_currency(item.price) %></td>
<td class="quantity"><%= quantity %><br /></td>
<td class="price">
<%= number_to_currency(quantity * item.price, :unit => "£") %>
</td>
<td><a href="/cart/remove/<%= item.id %>">Remove from Cart</a></td>
</tr>
<% total += quantity * item.price %>
<% end %>
<tr>
<td colspan="4">
<div class="total">Total:</div>
</td>
<td>
<div class="price"><%= number_to_currency(total, :unit => "€") %></div>
</td>
</tr>
</table>
<p>
<%= link_to 'Continue Shopping', :controller => :items %>
<%= link_to 'Clear Cart', :controller => "cart", :action => "clearCart" %>
<%= link_to 'Check Out', :controller => "cart", :action => "createOrder" %>
</p>